#%RAML 1.0
title: I18N API
version: v1
baseUri: http://api.i18n.bankbazaar.com
mediaType:
  - application/json
protocols:
  - HTTP

/bundle:
  /{bundleId}:
    /{sha}:
      get:
        description: Gives the js bundle for the given id and signature
        responses:
          200:
            body:
              application/javascript:

/sha:
  /{bundleId}:
    description: Get the sha value given a bundle
    get:
      responses:
        200:
          body:
            application/json:
              type: string


/admin:
  /bundle/{bundleId}:
    post:
      description: Generate the bundle from the latest configuration
      responses:
        200:
          body:
            application/json:
              type: string
        401:
          description: Non admin users cannot create the bundle
